apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datalake.fullname" . }}-hadoop-config
  labels:
    app.kubernetes.io/component: hadoop-config
data:
  core-site.xml: |
{{ .Files.Get "files/conf/hadoop/core-site.xml" | indent 4 }}
  hdfs-site.xml: |
{{ .Files.Get "files/conf/hadoop/hdfs-site.xml" | indent 4 }}
