apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datalake.fullname" . }}-hiveserver
  labels:
    app.kubernetes.io/component: hive-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: hive-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hive-server
    spec:
      containers:
      - name: hiveserver
        image: "{{ .Values.hive.hiveserver.image }}:{{ .Values.hive.hiveserver.tag }}"
        imagePullPolicy: IfNotPresent
        command: ["/opt/hive/bin/hive", "--service", "hiveserver2"]
        env:
        {{- range $key, $value := .Values.hadoop.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        ports:
        - name: hiveserver2
          containerPort: {{ .Values.hive.hiveserver.port }}
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
        - name: hadoop-config
          mountPath: /etc/hadoop
      volumes:
      - name: hive-config
        configMap:
          name: {{ include "datalake.fullname" . }}-hive-config
      - name: hadoop-config
        configMap:
          name: {{ include "datalake.fullname" . }}-hadoop-config
