apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datalake.fullname" . }}-sparkmaster
  labels:
    app.kubernetes.io/component: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: spark-master
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spark-master
    spec:
      containers:
      - name: sparkmaster
        image: "{{ .Values.spark.master.image }}:{{ .Values.spark.master.tag }}"
        imagePullPolicy: {{ .Values.spark.master.imagePullPolicy | default "IfNotPresent" }}
        env:
        {{- range $key, $value := .Values.hadoop.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        - name: INIT_DAEMON_STEP
          value: "{{ .Values.spark.master.env.INIT_DAEMON_STEP }}"
        - name: SPARK_LOCAL_IP
          value: "{{ .Values.spark.master.env.SPARK_LOCAL_IP }}"
        - name: SPARK_DRIVER_HOST
          value: "{{ .Values.spark.master.env.SPARK_DRIVER_HOST }}"
        - name: SPARK_DRIVER_BIND_ADDRESS
          value: "0.0.0.0"
        ports:
        - name: web
          containerPort: {{ .Values.spark.master.ports.web }}
        - name: master
          containerPort: {{ .Values.spark.master.ports.master }}
        volumeMounts:
        - name: hadoop-config
          mountPath: /etc/hadoop
        - name: hive-config
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-site.xml
      volumes:
      - name: hadoop-config
        configMap:
          name: {{ include "datalake.fullname" . }}-hadoop-config
      - name: hive-config
        configMap:
          name: {{ include "datalake.fullname" . }}-hive-config
