apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalake.fullname" . }}-trino-worker
  labels:
    app.kubernetes.io/component: trino-worker
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.trino.worker.ports.http }}
      targetPort: http
  selector:
    app.kubernetes.io/component: trino-worker
