apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalake.fullname" . }}-hivemetastore
  labels:
    app.kubernetes.io/component: hive-metastore
spec:
  type: ClusterIP
  ports:
    - name: thrift
      port: {{ .Values.hive.metastore.port }}
      targetPort: thrift
  selector:
    app.kubernetes.io/component: hive-metastore
