apiVersion: v1
kind: Service
metadata:
  name: {{ include "helper-func-example.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "helper-func-example.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80

